### ISSUE TITLE
this._server.once('listening', this._onceServerListening)

### ISSUE THREAD

**Issue by oyb001** [taskcluster/docker-exec-websocket-server#9]
@djmitche @
run node websocket_server.js failed,the fellow is error inf:

```
[root@docker01 src]# node websocket_server.js 
/usr/local/src/node-v0.12.0/node_modules/ws/lib/WebSocketServer.js:78
    this._server.once('listening', this._onceServerListening);
                 ^
TypeError: undefined is not a function
    at new WebSocketServer (/usr/local/src/node-v0.12.0/node_modules/ws/lib/WebSocketServer.js:78:18)
    at new DockerExecWebsocketServer (/usr/local/src/node-v0.12.0/node_modules/docker-exec-websocket-server/lib/server.js:346:19)
    at Object.<anonymous> (/usr/local/src/node-v0.12.0/node_modules/docker-exec-websocket-server/src/websocket_server.js:7:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

#################websocket_server.js code############

> [root@docker01 src]# pwd
/usr/local/src/node-v0.12.0/node_modules/docker-exec-websocket-server/src
[root@docker01 src]# ls
client.js  messagecodes.js  server.js  websocket_server.js
[root@docker01 src]# cat websocket_server.js 
/**
 * Created by ouyangbin on 2016/9/20.
 */
var DockerServer = require('../lib/server.js');
var http = require('http');
var slugid = require('slugid');
var dockerServer = new DockerServer({
  port:8080, //automatically creates http server
  //OR
  server:http, //http.Serv object, can also be https, should already be listening
  path: '/'+slugid.v4(),    //Path to WebSocket
  containerId: '082a83bfb58e',  //Container to inject exec proccess into
  dockerSocket: '/var/run/docker.sock', //location of docker remote API socket
  maxSessions: 10 //maximum number of connected sessions
});
//await dockerServer.execute();

[root@docker01 src]# 

=============the fellow is run npm test result=================
testserver
[root@docker01 docker-exec-websocket-server]# npm test

> docker-exec-websocket-server@1.3.1 test /usr/local/src/node-v0.12.0/node_modules/docker-exec-websocket-server
> ./test/runtests.sh

**#!/bin/bash -ve
# USAGE: Run this file using `npm test` (must run from repository root)**

npm run compile;

> docker-exec-websocket-server@1.3.1 compile /usr/local/src/node-v0.12.0/node_modules/docker-exec-websocket-server
> babel -d lib/ src/


docker run --rm  --name testserver ubuntu sleep 60 &
trap "docker kill testserver;" EXIT; sleep 1;
WARNING: IPv4 forwarding is disabled. Networking will not work.

mocha \
  test/test.js


  trying client
Exit code: 0
stdout: ''
stderr: ''
    ✓ docker exec wc -c (40ms)
    ✓ cat on server (260ms)
    ✓ exit code (259ms)
    ✓ connection limit 
    ✓ automatic pausing (1005ms)
    ✓ session count 
    ✓ resize (3261ms)


  7 passing (11s)


eslint \
  src/server.js \
  src/client.js 
docker kill testserver;
testserver
[root@docker01 docker-exec-websocket-server]# pwd
/usr/local/src/node-v0.12.0/node_modules/docker-exec-websocket-server
[root@docker01 docker-exec-websocket-server]# 
```

**Comment by jonasfj** [comment]
Try with recent version of node..

I assume you are playing with docker-exec-websocket-server?

Den 19. sep. 2016 8.24 PM skrev "oyb001" notifications@github.com:

**Comment by oyb001** [comment]
# "docker-exec-websocket-server" version is "1.3.1",According to the requirements of our package installed node 0.12.0

[root@docker01 src]# node -v
v0.12.0
[root@docker01 src]#

**Comment by jwhitlock** [comment]
Closing this 2016 issue. Feel free to re-open or recreate with the current code base and Node versions.
